[build]
  command = "npm run build"
  publish = "public"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-gatsby"
